- name: Downloading {{COMPONENT}} Repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing {{COMPONENT}} packages
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Installing {{COMPONENT}} -shell
  ansible.builtin.dnf:
    name: mongodb-org-shell
    state: installed

- name: Enabling {{COMPONENT}} visibility
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
    #remote_src: yes

- name: Starting {{COMPONENT}} Services
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
    daemon_reload: yes

- name: Downloading and Extracting {{COMPONENT}} Schema
  ansible.builtin.unarchive:
  src: https://github.com/stans-robot-project/mongodb/archive/main.zip
  dest: /tmp
  remote_src: yes

- name: Inject the Schema
  ansible.builtin.shell: mongo --host mongodb-{{ENV}}.roboshop.internal < /tmp/mongodb-main/{{item}}.js
  loop:
    - catalogue
    - users

- name: Set HostName 
  ansible.builtin.shell: set-hostname {{COMPONENT}}






