# Variable Precendece : cli variables > task variables > play variables

### When to use quotes and when not to use quotes in YAML while dealing with variables ?

###  ---> if in your print msg, if you just have varaible, then it's a must to enclose them in "" 's  --> msg: "{{CITY}}"

- name: Demo On Variables
  hosts: all
  vars:
    URL: play.google.com
  #gather_facts: false  --> If ou dont want ansible to gather facts before exctn ...observe OK=3/4 its by default includes gather_facts if you dont disbale it.
  tasks:
    - name: Printing the Var value from Play
      ansible.builtin.debug:
        msg: Value of the play Variable is {{URL}}


    - name: Printing the Var value from tasks
      ansible.builtin.debug:
        msg: Value of the task variable is {{URL}}
      vars:
        URL: task.google.com

    - name: Printing the Var value which is not declared
      ansible.builtin.debug:
        msg: Value of the undeclared Variable is {{CITY}}

    - name: Printing OS Distro
      ansible.builtin.debug:
        msg: My OS Distro is  {{ansible_distribution}}

# Can supply var value from cmd line arg (cli)---> ansible-playbook -i inv -e ansible_user=centos -e ansible_password=DevOps321 -e CITY=Bangalore 002-vars.yaml

# If you want to change the existing value of the var you can do it through cli 
#ansible-playbook -i inv -e ansible_user=centos -e ansible_password=DevOps321 -e CITY=Bangalore -e URL=cli.google.com 002-vars.yaml






    
