#gather_facts: false  --> If ou dont want ansible to gather facts before exctn ...observe OK=3/4 its by default includes gather_facts if you dont disbale it.

# Whenever ansible runs the playbook, it fist collects the properties of all the machines and then it will start doing the CM
# What is a FACT ?
# A fact nothing but the properties of the VM's. 

# In ansible, if you attempt to print a variable that is not decalred, ANSIBLE throws an exception!

# Cmd to gather facts is : ansible all -i inv -e ansible_user=centos -e ansible_password=DevOps321 -m gather_facts
# the above cmd gives out put in json format
- name: Demo On Vars 
  hosts: all 
  vars:                          # Play level variables : if you declare a variable at play level, all tasks of the play      inherit them
    URL: play.google.com
  gather_facts: false      
  tasks:
    - name: printing url
      ansible.builtin.debug:
        msg: Value of URL is {{URL}}      # in bash, we use "echo $URL"

    - name: printing url from task 
      ansible.builtin.debug:
        msg: Value of URL is {{URL}}      
      vars:                              # Task level variables : if you declare a variable at task level,only that task can use
        URL: task.google.com

    # - name: Printing city name
    #   ansible.builtin.debug:
    #     msg: "{{CITY}}"     

    - name: Printing OD Distro
      ansible.builtin.debug:
        msg: My OS Distro is {{ansible_distribution}} 

