- name: Demo on using shell module
  hosts: all
  tasks:
    - name: Running uptime shell cmd
      ansible.builtin.shell: uptime    # By default shell cmd will not print the result 
      register: OUT

    - name: Printing the result of shell cmd
      ansible.builtin.debug:
        msg: "{{OUT}}"

    - name: Printing only the exitcode
      ansible.builtin.set_fact:
        EXITCODE: "{{OUT.rc}}"
        msg: The exitcode of the last exctd cmd is {{EXITCODE}}

    - name: Printing uptime 
      ansible.builtin.debug:
        msg: Uptime of the server is {{OUT.stdout}}
