- name: Demo on using shell module
  hosts: all
  tasks:
    - name: Running uptime shell cmd
      ansible.builtin.shell: uptime    # By default shell cmd will not print the result 
      register: OUT

    - name: Printing the result of shell cmd
      ansible.builtin.debug:
        msg: "{{OUT}}"
