- name: Demo On Conditions
  hosts: all
  vars: 
    flag: true
  tasks:
    - name: Run this only when the distro is Centos
      ansible.builtin.debug:
        msg: OS Distro is {{ansible_distribution}}
      when: ansible_distribution == "CentOS"

    - name: Run this only when the distro is Ubuntu
      ansible.builtin.debug:
        msg: OS Distro is {{ansible_distribution}}

    - name: Run the flag
      ansible.builtin.debug:
        msg: flag is true
      when: flag 

    - name: Run this when variable is not defined
      ansible.builtin.debug:
        msg: variable is not defined
      when: Varbl is not defined