- name: Demo Using Tags
  hosts: all
  tasks:
    - name: Installing Frontend
      ansible.builtin.debug:
        msg: Installing Frontend 
      tags: frontend


    - name: Starting Frontend
      ansible.builtin.debug:
        msg: Starting Frontend
      tags: frontend



    - name: Installing App
      ansible.builtin.debug:
        msg: Installing App 
      tags: app


    - name: Starting App
      ansible.builtin.debug:
        msg: Starting App 
      tags: app



    - name: Installing DB
      ansible.builtin.debug:
        msg: Installing DB 
      tags: db


    - name: Starting DB
      ansible.builtin.debug:
        msg: Starting DB
      tags: db

# cmd to run with tag name is: ansible-playbook -i inv -e ansible_user=centos -e ansible_password=DevOps321 007-tags.yaml -t app



