- name: Demo on Running Play as User/ Root User/
  hosts: all
  tasks:
    - name: Checking User
      ansible.builtin.shell: id 
      register: OUT
    
    - name: Printing the User details
      ansible.builtin.debug:
        msg: "User Details are {{OUT}}"