- name: Set HostName
  ansible.builtin.shell: set-hostname {{COMPONENT}}

- name: Disable NodeJS-10 and Enable NodeJS-18
  ansible.builtin.shell: dnf module disable nodejs -y && dnf module enable nodejs:18 -y

- name: Installing NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Adding {{APPUSER}} user account
  ansible.builtin.user:
    name: "{{APPUSER}}"

- name: Download and Extract {{COMPONENT}} Artifacts
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/user/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Performing Cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent

- name: Copying Files to {{APPUSER}} Dir
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main
    dest: /home/{{APPUSER}}/{{COMPONENT}}
    remote_src: yes

- name: Changing the ownership of the Artifacts
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"

- name: Install node.js packages
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}

- name: Configuring related IP's 
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Starting {{COMPONENT}} Services
  ansible.builtin.service:
    name: "{{COMPONENT}}"
    state: started
    enabled: yes
    daemon_reload: yes
  